### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by arubislander** [arubislander/docker-subsonic#1]
This project needs some documentation on the purpose and use of this image.

**Comment by b4r0z** [comment]
yes please :)

**Comment by arubislander** [comment]
Hi,

Thanks for reaching out and showing an interest in the docker image.

Yes, the subsonic preferences are not persisted between container
instances. I moved on from this project before tackling that issue. But I
do have some ideas how that could be handled, but I have not looked into
their feasibility.

The first solution that comes to mind is to mount a subsonic configuration
file to the right location in the container. I don't have the correct
location on hand at the moment.

Another possibility is to mount a named data container to  /var/subsonic in
the container. That should persist the settings between docker container
instance creations. But again, I haven't tested this theory myself.

Thanks again for reaching out.
Terence

**Comment by b4r0z** [comment]
hi,
with Openmediavault I managed somehow to save the subsonic docker configuration.

Thank you for your work, it is running great on my small Banana Pi.
Only downside is the time needed to start the image (about a couple of hours) but the library is pretty huge [Sorriso]
The old subsonic plugin for openmediavault used to be faster, dont’ know why.
Nevertheless Libresonic doker image is waaaaay slower!!

Thank you again, I now enjoy my library all over arond the word
Enrico

**Comment by arubislander** [comment]
Ah, you're running docker on OMV. I have no experience with such a setup.

**Comment by arubislander** [comment]
Expired...
